### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by akashdeepjassal** [timesler/facenet-pytorch#24]
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-ad8fca11d4e4>", line 1, in <module>
    from facenet_pytorch import MTCNN, InceptionResnetV1, prewhiten, training

  File "/home/flash/Desktop/akash/new/Pytorch-Facenet/facenet_pytorch/__init__.py", line 4, in <module>
    from .models.utils import training

  File "/home/flash/Desktop/akash/new/Pytorch-Facenet/facenet_pytorch/models/utils/training.py", line 18
    track_str = f'\r{self.mode} | {i + 1:5d}/{self.length:<5d}| '
                                                                ^
SyntaxError: invalid syntax

**Comment by timesler** [comment]
Thanks for letting me know, this is a python 3.5 compatibility issue that I forgot to check. I've corrected it in the latest version of the python package (v0.2.3), and will merge it into master very shortly (just waiting for CI tests to run).

You can get the fixed package with `pip install --upgrade facenet-pytorch`
